import Decimal from 'decimal.js';
import { formatIsoDate } from '@financialos/ui';

/** Rounds a decimal string for display (e.g. runway months). Never used for amounts of record. */
export function formatDecimal(value: string | null | undefined, places = 1): string | null {
  if (!value || !/^-?\d+(\.\d+)?$/.test(value)) return null;
  return new Decimal(value).toDecimalPlaces(places, Decimal.ROUND_HALF_EVEN).toFixed(places);
}

/** Share expressed as a decimal fraction string ("0.42") → "42%". */
export function formatShare(value: string | null | undefined): string | null {
  if (!value || !/^-?\d+(\.\d+)?$/.test(value)) return null;
  return `${new Decimal(value).times(100).toDecimalPlaces(0).toFixed(0)}%`;
}

/** Fraction for progress-bar geometry only. */
export function geometryFraction(value: string | null | undefined): number | null {
  if (!value || !/^-?\d+(\.\d+)?$/.test(value)) return null;
  return new Decimal(value).toNumber();
}

export function ratioForGeometry(part: string | null | undefined, whole: string | null | undefined): number | null {
  if (!part || !whole || !/^-?\d+(\.\d+)?$/.test(part) || !/^-?\d+(\.\d+)?$/.test(whole)) return null;
  const w = new Decimal(whole);
  if (w.isZero()) return null;
  return new Decimal(part).dividedBy(w).toNumber();
}

export function formatDate(iso: string | null | undefined, style: 'short' | 'medium' | 'long' = 'medium'): string {
  if (!iso) return '—';
  return formatIsoDate(iso.slice(0, 10), style);
}

export function todayLong(): string {
  return new Intl.DateTimeFormat('en-GB', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date());
}

export function daysUntil(isoDate: string, now: Date = new Date()): number {
  const [y, m, d] = isoDate.split('-').map((p) => Number.parseInt(p, 10));
  const target = Date.UTC(y ?? 1970, (m ?? 1) - 1, d ?? 1);
  const today = Date.UTC(now.getFullYear(), now.getMonth(), now.getDate());
  return Math.round((target - today) / 86_400_000);
}

export function relativeDay(isoDate: string): string {
  const n = daysUntil(isoDate);
  if (n === 0) return 'Today';
  if (n === 1) return 'Tomorrow';
  if (n === -1) return 'Yesterday';
  if (n > 1 && n < 7) return `In ${n} days`;
  if (n < 0) return `${-n} days ago`;
  return formatDate(isoDate, 'short');
}

export function humanList(items: string[]): string {
  if (items.length <= 1) return items.join('');
  return `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;
}

/** "Generated by: deterministic rules" or the model name — never a mislabel. */
export function generatedByLabel(generatedBy: string): string {
  const v = generatedBy.trim();
  if (!v || v === 'deterministic' || v === 'rules' || v.startsWith('deterministic')) return 'deterministic rules';
  return v;
}
